### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'int' and 'str'

### ISSUE THREAD

**Issue by Deep1994** [uclanlp/synpg#6]
Hi, when I run train.syng.sh, I get an error:

Traceback (most recent call last):
  File "train_synpg.py", line 285, in <module>
    train(epoch, model, train_data, valid_data, train_loader, valid_loader, optimizer, criterion, dictionary, bpe, args)
  File "train_synpg.py", line 90, in train
    sent_ = bpe.segment(sent_).split()
  File "/home/dingp/synpg-master/subwordnmt/apply_bpe.py", line 59, in segment
    new_word = [out for segment in self._isolate_glossaries(word)
  File "/home/dingp/synpg-master/subwordnmt/apply_bpe.py", line 60, in <listcomp>
    for out in encode(segment,
  File "/home/dingp/synpg-master/subwordnmt/apply_bpe.py", line 144, in encode
    word = tuple(orig[:-1]) + ( orig[-1] + '</w>',)
TypeError: unsupported operand type(s) for +: 'int' and 'str'

It seems something wrong with the BPE?   Could you help me ? thanks !

**Comment by Deep1994** [comment]
I print(orig) and print(orig[-1]), the out is :
b'`'
96

**Comment by NIL-zhuang** [comment]
hello, I encountered the same problem, how did you fixed it?

**Comment by ej0cl6** [comment]
I guess it's probably caused by the package version. Did you install all the corresponding packages as suggested?

**Comment by NIL-zhuang** [comment]
oh, I found I installed the wrong h5py, thank you for your kind reply
